const mongoose = require('mongoose');
require('dotenv').config();

const User = require('../models/User');
const RTI = require('../models/RTI');

const dummyRTIs = [
  {
    applicantName: 'James Kirwin',
    gender: 'Male',
    email: 'james.kirwin@gmail.com',
    contactNumber: '+91 9876543210',
    address: 'Suite No. 309, Third Floor, Infinity Tower, Sector 63, Noida, UP 201309',
    rtiCaseNumber: 'RTI/2025/MAN/0001',
    subject: 'RTI/2025/MAN/0001',
    description: 'Request for information regarding departmental budget allocation for FY 2024-25.',
    applicationMode: 'Online',
    department: 'Manager',
    assignedOfficer: 'Mr. Rajesh Kumar',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    extendedDueDate: new Date('2026-01-24'),
    reminderFrequency: '3 Days',
    status: 'Verified',
  },
  {
    applicantName: 'Francis Chang',
    gender: 'Male',
    email: 'francis.chang@outlook.com',
    contactNumber: '+91 9123456789',
    address: '42, Park Avenue, Connaught Place, New Delhi 110001',
    rtiCaseNumber: 'RTI/2025/SUP/0001',
    subject: 'RTI/2025/SUP/0001',
    description: 'Seeking details on recruitment process and vacancies in the Supervisor department.',
    applicationMode: 'Offline',
    department: 'Supervisor',
    assignedOfficer: 'Ms. Priya Sharma',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Weekly',
    status: 'Pending',
  },
  {
    applicantName: 'Antonio Engle',
    gender: 'Male',
    email: 'antonio.engle@yahoo.com',
    contactNumber: '+91 8899776655',
    address: '15-B, Banjara Hills, Hyderabad, Telangana 500034',
    rtiCaseNumber: 'RTI/2025/MAN/0002',
    subject: 'RTI/2025/MAN/0002',
    description: 'Information about tender documents and contracts awarded in the last fiscal year.',
    applicationMode: 'Email',
    department: 'Manager',
    assignedOfficer: 'Mr. Amit Singh',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Daily',
    status: 'Draft',
  },
  {
    applicantName: 'Leo Kelly',
    gender: 'Male',
    email: 'leo.kelly@company.org',
    contactNumber: '+91 7766554433',
    address: '78, MG Road, Bengaluru, Karnataka 560001',
    rtiCaseNumber: 'RTI/2025/SUP/0002',
    subject: 'RTI/2025/SUP/0002',
    description: 'Request for copies of circulars issued regarding employee welfare schemes.',
    applicationMode: 'Post',
    department: 'Supervisor',
    assignedOfficer: 'Ms. Neha Gupta',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    extendedDueDate: new Date('2026-02-10'),
    reminderFrequency: 'Monthly',
    status: 'Rejected',
  },
  {
    applicantName: 'Annette Walker',
    gender: 'Female',
    email: 'annette.walker@mail.com',
    contactNumber: '+91 9988776655',
    address: '301, Sapphire Residency, Andheri West, Mumbai, MH 400053',
    rtiCaseNumber: 'RTI/2025/ACC/0001',
    subject: 'RTI/2025/ACC/0001',
    description: 'Details of expenditure incurred on infrastructure development in 2024-25.',
    applicationMode: 'Online',
    department: 'Accountant',
    assignedOfficer: 'Mr. Vikram Patel',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: '3 Days',
    status: 'Verified',
  },
  {
    applicantName: 'James Kirwin',
    gender: 'Male',
    email: 'james.kirwin2@gmail.com',
    contactNumber: '+91 9876543211',
    address: 'Flat 12A, Green Park, New Delhi 110016',
    rtiCaseNumber: 'RTI/2025/SUP/0003',
    subject: 'RTI/2025/SUP/0003',
    description: 'Information regarding pending grievance redressal cases in the department.',
    applicationMode: 'Online',
    department: 'Supervisor',
    assignedOfficer: 'Ms. Priya Sharma',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Weekly',
    status: 'Draft',
  },
  {
    applicantName: 'Francis Chang',
    gender: 'Male',
    email: 'francis.chang2@outlook.com',
    contactNumber: '+91 9123456790',
    address: '88, Lake Town, Kolkata, West Bengal 700089',
    rtiCaseNumber: 'RTI/2025/ACC/0002',
    subject: 'RTI/2025/ACC/0002',
    description: 'Seeking information on salary disbursement records for contractual employees.',
    applicationMode: 'Offline',
    department: 'Accountant',
    assignedOfficer: 'Mr. Rajesh Kumar',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Daily',
    status: 'Pending',
  },
  {
    applicantName: 'Antonio Engle',
    gender: 'Male',
    email: 'antonio.engle2@yahoo.com',
    contactNumber: '+91 8899776656',
    address: '22, Civil Lines, Jaipur, Rajasthan 302006',
    rtiCaseNumber: 'RTI/2025/SUP/0004',
    subject: 'RTI/2025/SUP/0004',
    description: 'Request for details on internal audit reports for the previous two financial years.',
    applicationMode: 'Email',
    department: 'Supervisor',
    assignedOfficer: 'Mr. Amit Singh',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: '3 Days',
    status: 'Rejected',
  },
  {
    applicantName: 'Leo Kelly',
    gender: 'Male',
    email: 'leo.kelly2@company.org',
    contactNumber: '+91 7766554434',
    address: '55, Whitefield Main Road, Bengaluru, Karnataka 560066',
    rtiCaseNumber: 'RTI/2025/ACC/0003',
    subject: 'RTI/2025/ACC/0003',
    description: 'Information on travel reimbursements claimed by senior officials in 2024.',
    applicationMode: 'Online',
    department: 'Accountant',
    assignedOfficer: 'Ms. Neha Gupta',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Weekly',
    status: 'Verified',
  },
  {
    applicantName: 'Annette Walker',
    gender: 'Female',
    email: 'annette.walker2@mail.com',
    contactNumber: '+91 9988776656',
    address: '9, Jubilee Hills, Hyderabad, Telangana 500033',
    rtiCaseNumber: 'RTI/2025/SUP/0005',
    subject: 'RTI/2025/SUP/0005',
    description: 'Requesting information on the status of pending RTI appeals in the department.',
    applicationMode: 'Post',
    department: 'Supervisor',
    assignedOfficer: 'Mr. Vikram Patel',
    dateOfReceipt: new Date('2025-12-10'),
    dueDate: new Date('2026-01-10'),
    reminderFrequency: 'Monthly',
    status: 'Pending',
  },
  {
    applicantName: 'Hendry Peralt',
    gender: 'Male',
    email: 'info@alobhatechnologies.com',
    contactNumber: '+91 9876543210',
    address: 'Suite No. 309, Third Floor, Infinity Tower, H-221, H Block, Sector 63, Noida, Uttar Pradesh 201309',
    rtiCaseNumber: 'RTI/2026/ACC/0001',
    subject: 'RTI/2026/ACC/0001',
    description: 'Printers in the 1500s scrambled the words from Cicero\'s "De Finibus Bonorum et Malorum" after mixing the words in each sentence. The familiar "lorem ipsum dolor sit amet" text emerged when 16th-century printers adapted Cicero\'s original work, beginning with the phrase "dolor sit amet consectetur." They abbreviated "dolorem".',
    applicationMode: 'Online',
    department: 'Accountant',
    assignedOfficer: 'Mr. Rajesh Kumar',
    dateOfReceipt: new Date('2026-03-25'),
    dueDate: new Date('2026-04-12'),
    extendedDueDate: new Date('2026-04-24'),
    reminderFrequency: '3 Days',
    status: 'Verified',
  },
  {
    applicantName: 'Priya Mehta',
    gender: 'Female',
    email: 'priya.mehta@gmail.com',
    contactNumber: '+91 8765432109',
    address: '14, Shastri Nagar, Lucknow, Uttar Pradesh 226001',
    rtiCaseNumber: 'RTI/2026/HR/0001',
    subject: 'RTI/2026/HR/0001',
    description: 'Request for details on employee promotion policy and criteria for the year 2025-26.',
    applicationMode: 'Online',
    department: 'HR',
    assignedOfficer: 'Ms. Priya Sharma',
    dateOfReceipt: new Date('2026-01-15'),
    dueDate: new Date('2026-02-15'),
    reminderFrequency: 'Weekly',
    status: 'Pending',
  },
  {
    applicantName: 'Suresh Reddy',
    gender: 'Male',
    email: 'suresh.reddy@outlook.com',
    contactNumber: '+91 7654321098',
    address: '203, Ameerpet, Hyderabad, Telangana 500016',
    rtiCaseNumber: 'RTI/2026/LEG/0001',
    subject: 'RTI/2026/LEG/0001',
    description: 'Seeking copies of legal opinions provided to the university on land acquisition matters.',
    applicationMode: 'Offline',
    department: 'Legal',
    assignedOfficer: 'Mr. Amit Singh',
    dateOfReceipt: new Date('2026-02-01'),
    dueDate: new Date('2026-03-01'),
    extendedDueDate: new Date('2026-03-15'),
    reminderFrequency: '3 Days',
    status: 'Verified',
  },
  {
    applicantName: 'Kavita Sharma',
    gender: 'Female',
    email: 'kavita.sharma@corp.in',
    contactNumber: '+91 6543210987',
    address: '77, Aundh, Pune, Maharashtra 411007',
    rtiCaseNumber: 'RTI/2026/IT/0001',
    subject: 'RTI/2026/IT/0001',
    description: 'Information regarding IT infrastructure upgrade costs and vendor contracts for 2025-26.',
    applicationMode: 'Email',
    department: 'IT',
    assignedOfficer: 'Ms. Neha Gupta',
    dateOfReceipt: new Date('2026-02-20'),
    dueDate: new Date('2026-03-20'),
    reminderFrequency: 'Daily',
    status: 'Rejected',
  },
  {
    applicantName: 'Rahul Verma',
    gender: 'Male',
    email: 'rahul.verma@proton.me',
    contactNumber: '+91 5432109876',
    address: '10, Gomti Nagar, Lucknow, Uttar Pradesh 226010',
    rtiCaseNumber: 'RTI/2026/FIN/0001',
    subject: 'RTI/2026/FIN/0001',
    description: 'Request for audited financial statements and balance sheet for FY 2024-25.',
    applicationMode: 'Post',
    department: 'Finance',
    assignedOfficer: 'Mr. Vikram Patel',
    dateOfReceipt: new Date('2026-03-05'),
    dueDate: new Date('2026-04-05'),
    reminderFrequency: 'Monthly',
    status: 'Draft',
  },
  {
    applicantName: 'Deepa Nair',
    gender: 'Female',
    email: 'deepa.nair@yahoo.co.in',
    contactNumber: '+91 4321098765',
    address: '55, Marine Drive, Ernakulam, Kerala 682031',
    rtiCaseNumber: 'RTI/2026/ADM/0001',
    subject: 'RTI/2026/ADM/0001',
    description: 'Details on administrative restructuring plans and new department creation proposals.',
    applicationMode: 'Online',
    department: 'Administration',
    assignedOfficer: 'Mr. Rajesh Kumar',
    dateOfReceipt: new Date('2026-03-10'),
    dueDate: new Date('2026-04-10'),
    reminderFrequency: '3 Days',
    status: 'Pending',
  },
  {
    applicantName: 'Amit Saxena',
    gender: 'Male',
    email: 'amit.saxena@live.com',
    contactNumber: '+91 3210987654',
    address: '33, Hazratganj, Lucknow, Uttar Pradesh 226001',
    rtiCaseNumber: 'RTI/2026/MAN/0001',
    subject: 'RTI/2026/MAN/0001',
    description: 'Request for minutes of management committee meetings held in Q3 2025.',
    applicationMode: 'Offline',
    department: 'Manager',
    assignedOfficer: 'Ms. Priya Sharma',
    dateOfReceipt: new Date('2026-03-18'),
    dueDate: new Date('2026-04-18'),
    reminderFrequency: 'Weekly',
    status: 'Verified',
  },
  {
    applicantName: 'Neelam Joshi',
    gender: 'Female',
    email: 'neelam.joshi@gmail.com',
    contactNumber: '+91 2109876543',
    address: '120, Vaishali Nagar, Jaipur, Rajasthan 302021',
    rtiCaseNumber: 'RTI/2026/HR/0002',
    subject: 'RTI/2026/HR/0002',
    description: 'Seeking information on diversity and inclusion initiatives undertaken in the last year.',
    applicationMode: 'Online',
    department: 'HR',
    assignedOfficer: 'Mr. Amit Singh',
    dateOfReceipt: new Date('2026-04-01'),
    dueDate: new Date('2026-05-01'),
    reminderFrequency: 'Daily',
    status: 'Pending',
  },
  {
    applicantName: 'Vikrant Tiwari',
    gender: 'Male',
    email: 'vikrant.tiwari@tech.io',
    contactNumber: '+91 1098765432',
    address: '8, Koramangala, Bengaluru, Karnataka 560034',
    rtiCaseNumber: 'RTI/2026/IT/0002',
    subject: 'RTI/2026/IT/0002',
    description: 'Information about cybersecurity audits conducted and vulnerabilities reported in 2025.',
    applicationMode: 'Email',
    department: 'IT',
    assignedOfficer: 'Ms. Neha Gupta',
    dateOfReceipt: new Date('2026-04-05'),
    dueDate: new Date('2026-05-05'),
    extendedDueDate: new Date('2026-05-20'),
    reminderFrequency: '3 Days',
    status: 'Draft',
  },
  {
    applicantName: 'Sonal Gupta',
    gender: 'Female',
    email: 'sonal.gupta@university.edu',
    contactNumber: '+91 9871234560',
    address: '45, Saket, New Delhi 110017',
    rtiCaseNumber: 'RTI/2026/FIN/0002',
    subject: 'RTI/2026/FIN/0002',
    description: 'Request for details on grants received from central government and their utilization.',
    applicationMode: 'Online',
    department: 'Finance',
    assignedOfficer: 'Mr. Vikram Patel',
    dateOfReceipt: new Date('2026-04-12'),
    dueDate: new Date('2026-05-12'),
    reminderFrequency: 'Weekly',
    status: 'Verified',
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Seed admin user
    const existingAdmin = await User.findOne({ email: 'admin@rti.com' });
    if (existingAdmin) {
      console.log('Admin user already exists');
    } else {
      await User.create({
        name: 'Admin User',
        email: 'admin@rti.com',
        password: 'admin123',
        role: 'admin',
      });
      console.log('Default admin user created successfully');
    }

    // Seed RTI records
    const existingCount = await RTI.countDocuments();
    if (existingCount > 0) {
      console.log(`${existingCount} RTI records already exist — skipping RTI seed`);
    } else {
      await RTI.insertMany(dummyRTIs);
      console.log(`${dummyRTIs.length} dummy RTI records seeded successfully`);
    }

    await mongoose.disconnect();
    console.log('Done. Disconnected from MongoDB');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error.message);
    await mongoose.disconnect();
    process.exit(1);
  }
};

seed();
